/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ResultadoCompletoRouteImport } from './routes/resultado-completo'
import { Route as ResultRouteImport } from './routes/result'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as LeadRouteImport } from './routes/lead'
import { Route as ConfirmacaoRouteImport } from './routes/confirmacao'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as QuizStepRouteImport } from './routes/quiz/$step'
import { Route as CheckoutOrderIdRouteImport } from './routes/checkout.$orderId'
import { Route as AdminLoginRouteImport } from './routes/admin/login'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadoCompletoRoute = ResultadoCompletoRouteImport.update({
  id: '/resultado-completo',
  path: '/resultado-completo',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadRoute = LeadRouteImport.update({
  id: '/lead',
  path: '/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacaoRoute = ConfirmacaoRouteImport.update({
  id: '/confirmacao',
  path: '/confirmacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizStepRoute = QuizStepRouteImport.update({
  id: '/quiz/$step',
  path: '/quiz/$step',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOrderIdRoute = CheckoutOrderIdRouteImport.update({
  id: '/checkout/$orderId',
  path: '/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/lead': typeof LeadRoute
  '/oferta': typeof OfertaRoute
  '/processing': typeof ProcessingRoute
  '/result': typeof ResultRoute
  '/resultado-completo': typeof ResultadoCompletoRoute
  '/upload': typeof UploadRoute
  '/admin/login': typeof AdminLoginRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/quiz/$step': typeof QuizStepRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/lead': typeof LeadRoute
  '/oferta': typeof OfertaRoute
  '/processing': typeof ProcessingRoute
  '/result': typeof ResultRoute
  '/resultado-completo': typeof ResultadoCompletoRoute
  '/upload': typeof UploadRoute
  '/admin/login': typeof AdminLoginRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/quiz/$step': typeof QuizStepRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/lead': typeof LeadRoute
  '/oferta': typeof OfertaRoute
  '/processing': typeof ProcessingRoute
  '/result': typeof ResultRoute
  '/resultado-completo': typeof ResultadoCompletoRoute
  '/upload': typeof UploadRoute
  '/admin/login': typeof AdminLoginRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/quiz/$step': typeof QuizStepRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirmacao'
    | '/lead'
    | '/oferta'
    | '/processing'
    | '/result'
    | '/resultado-completo'
    | '/upload'
    | '/admin/login'
    | '/checkout/$orderId'
    | '/quiz/$step'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirmacao'
    | '/lead'
    | '/oferta'
    | '/processing'
    | '/result'
    | '/resultado-completo'
    | '/upload'
    | '/admin/login'
    | '/checkout/$orderId'
    | '/quiz/$step'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/confirmacao'
    | '/lead'
    | '/oferta'
    | '/processing'
    | '/result'
    | '/resultado-completo'
    | '/upload'
    | '/admin/login'
    | '/checkout/$orderId'
    | '/quiz/$step'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmacaoRoute: typeof ConfirmacaoRoute
  LeadRoute: typeof LeadRoute
  OfertaRoute: typeof OfertaRoute
  ProcessingRoute: typeof ProcessingRoute
  ResultRoute: typeof ResultRoute
  ResultadoCompletoRoute: typeof ResultadoCompletoRoute
  UploadRoute: typeof UploadRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CheckoutOrderIdRoute: typeof CheckoutOrderIdRoute
  QuizStepRoute: typeof QuizStepRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultado-completo': {
      id: '/resultado-completo'
      path: '/resultado-completo'
      fullPath: '/resultado-completo'
      preLoaderRoute: typeof ResultadoCompletoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead': {
      id: '/lead'
      path: '/lead'
      fullPath: '/lead'
      preLoaderRoute: typeof LeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacao': {
      id: '/confirmacao'
      path: '/confirmacao'
      fullPath: '/confirmacao'
      preLoaderRoute: typeof ConfirmacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$step': {
      id: '/quiz/$step'
      path: '/quiz/$step'
      fullPath: '/quiz/$step'
      preLoaderRoute: typeof QuizStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$orderId': {
      id: '/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId'
      preLoaderRoute: typeof CheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmacaoRoute: ConfirmacaoRoute,
  LeadRoute: LeadRoute,
  OfertaRoute: OfertaRoute,
  ProcessingRoute: ProcessingRoute,
  ResultRoute: ResultRoute,
  ResultadoCompletoRoute: ResultadoCompletoRoute,
  UploadRoute: UploadRoute,
  AdminLoginRoute: AdminLoginRoute,
  CheckoutOrderIdRoute: CheckoutOrderIdRoute,
  QuizStepRoute: QuizStepRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
